name: web_sass_sample
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: luis <luisvargastijerino@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
#  font_awesome: any # uncomment and change for latest version
  # tag::exclude[]
  font_awesome:
    path: ../../
  # end::exclude[]

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  sass_builder: ^2.1.2
